CREATE DATABASE IF NOT EXISTS `BELAJAR` ;
USE `BELAJAR`;

CREATE TABLE `USER_NOT_1NF` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);
-- CONOTOH TIDAK 1INF 
INSERT INTO `USER_NOT_1NF` (USERNAME, PASSWORD, EMAIL) VALUES ('admin', 'admin', 'admin@gmail.com , admin@gmail.com');


CREATE TABLE `USER_NOT_1NF` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
    PHONE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
)




INSERT INTO `USER_1NF` (NAME) VALUES ('admin');
INSERT INTO CONTACT_PERSON (NAME, PHONE, EMAIL) VALUES ('admin', '081234567890', 'admin@gmail.com');

INSERT INTO `USER_1NF` (NAME) VALUES ('admin2');
INSERT INTO CONTACT_PERSON (NAME , PHONE, EMAIL) VALUES ('ADMIN2',  '08345437890', 'admin2@gmail.com');

SELECT U.`ID` , U.`NAME` , `PHONE`, `EMAIL` FROM USER_1NF U, CONTACT_PERSON ;


CREATE Table pelanggan (
    ID_PELANGGAN INT PRIMARY KEY AUTO_INCREMENT,
    NAMA VARCHAR(50) NOT NULL
)

create table pesanan_pelanggan (
    ID_PESANAN INT PRIMARY KEY AUTO_INCREMENT,
    ID_PELANGGAN INT NOT NULL,
    TANGGAL_PESAN DATE NOT NULL,
    FOREIGN KEY (ID_PELANGGAN) REFERENCES PELANGGAN(ID_PELANGGAN)
)